### ISSUE TITLE
Support usernames that do not conform to docker container names

### ISSUE THREAD

**Issue by yuvipanda** [jupyter/dockerspawner#25]
Some authentication providers (cough mediawiki) allow a lot more characters classes than they should (mediawiki allows (, spaces, ), etc). Hashing or seperating 'userid' from 'username' would allow people with such special characters in their username to use jupyterhub.

**Comment by yuvipanda** [comment]
Looking at the User model, I see that there's already an internal 'id' property. This should be used, perhaps?

**Comment by yuvipanda** [comment]
Booh, this rabbit hole goes deep down :( Cookie names in jupyterhub are also using username, and those have restrictions as well...

**Comment by minrk** [comment]
Yup, we should be careful about normalizing names when using them in restricted contexts. I would prefer to keep using names and normalize them, rather than hashing or using user.id, but using the id would be the simplest robust solution.

**Comment by yuvipanda** [comment]
Normalization could be problematic - if we replaced '(', ' ' and ')' with '_', for example, 'YuviPanda (WMF)' and 'YuviPanda__WMF_' will clash, and allow one user to potentially overtake another.

**Comment by yuvipanda** [comment]
https://github.com/yuvipanda/dockerspawner/tree/hashed-names is an initial attempt, not even close enough, however.
