### ISSUE TITLE
does dockerspawner work on windows?

### ISSUE THREAD

**Issue by denfromufa** [jupyter/dockerspawner#28]

**Comment by jhamrick** [comment]
I don't believe JupyterHub is supported on Windows, so I would not expect dockerspawner to work. I don't know if anybody has actually tried it, though.

**Comment by minrk** [comment]
No, dockerspawner won't work on Windows because JupyterHub itself won't run on Windows. I suppose it could work if you ran JupyterHub itself in a docker container on the Windows machine, though.

**Comment by ssanderson** [comment]
@minrk docker containers still share the kernel of their operating system host, so running JupyterHub in a docker container on Windows would also require running that container in a VM...at which point you're not really running on Window anyway.

**Comment by denfromufa** [comment]
Supposedly docker containers are coming to Windows Server

**Comment by minrk** [comment]
Docker on Windows generally means boot2docker, so the 'host' is actually a Linux VM already. The same is true on OS X.

**Comment by rgbkrk** [comment]
> Supposedly docker containers are coming to Windows Server

It's certainly on [their agenda](http://azure.microsoft.com/blog/2014/10/15/new-windows-server-containers-and-azure-support-for-docker/).

For the purposes of Dockerspawner, it interacts with the Docker API. As long as it supports the API properly, that's the path.

The Docker Engine for Windows Server doesn't exist yet, but if I had to guess they'll be running their own stripped down version of Linux to make it possible. It does have to be POSIX compatible after all.

**Comment by amellnik** [comment]
Jupyterhub works on Windows from within a docker container if you use Oauth and either simplespawner (for testing only) or dockerspawner (binding to the docker socket on the host and creating the single notebook containers on the same network).
