### ISSUE TITLE
Can't run the dockerspawner example

### ISSUE THREAD

**Issue by benjaminabel** [jupyter/dockerspawner#32]
Hi, I made some changes to the repo( see #30 #31) to reflect recent changes on jupyter, however when running th script  `run.sh`, I get the following error even if I correctly completed the env variables form github and the userlist. 
```
[W 2015-04-13 10:54:03.819 JupyterHub app:251] 
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
    
[E 2015-04-13 10:54:03.873 JupyterHub app:726] Proxy appears to be running at http://*:8000/, but I can't access it (HTTP 403: Forbidden)
    Did CONFIGPROXY_AUTH_TOKEN change?
```

**Comment by puneetjindal** [comment]
@benjaminabel :I am getting the following error

>  Hub API listening on http://127.0.0.1:8081/hub/
[D 2017-04-20 07:02:36.047 JupyterHub orm:146] Fetching GET http://127.0.0.1:8001/api/routes
[E 2017-04-20 07:02:36.049 JupyterHub app:1139] Proxy appears to be running at http://*:8000/, but I can't access it (HTTP 403: Forbidden)
    Did CONFIGPROXY_AUTH_TOKEN change?
[D 2017-04-20 07:02:36.049 JupyterHub application:647] Exiting application: jupyterhub

**Comment by minrk** [comment]
@puneetjindal if the Hub should be starting the proxy, this means that a previous instance was started and is still running. You can shut it down by finding the 'configurable-http-proxy` process and killing it.
