### ISSUE TITLE
Docker registry image broken

### ISSUE THREAD

**Issue by remy-phelipot** [jupyter/dockerspawner#38]
The image released on the docker registry seems to be broken. When pulling the image, the following error message is displayed:

	$ docker pull jupyter/systemuser
	Pulling repository jupyter/systemuser
	de9dd2e506c0: Error pulling image (latest) from jupyter/systemuser, HTTP code 400 
	428b411c28f0: Download complete 
	435050075b3f: Download complete 
	9fd3c8c9af32: Download complete 
	6d4946999d4f: Download complete 
	9bd2d4fa7079: Download complete 
	d6d97543cd83: Download complete 
	7f13ac159046: Download complete 
	a15e944e9b19: Download complete 
	ee69352e1c03: Error pulling dependent layers 
	FATA[0012] Error pulling image (latest) from jupyter/systemuser, HTTP code 400

**Comment by rgbkrk** [comment]
I just pulled this a few seconds ago and it worked just fine.

```
$ docker pull jupyter/systemuser
latest: Pulling from jupyter/systemuser
ca0e662e9f21: Pull complete
adb64715f139: Pull complete
f938c4e2d319: Pull complete
dc66b6aa53e6: Pull complete
ee2b61b74c54: Pull complete
3d8555517fac: Pull complete
1fabc29e3f22: Pull complete
3a459dba9e43: Pull complete
4f15fc1aec43: Pull complete
3aee375618c8: Pull complete
fb80f7acfb77: Pull complete
f0aff9699189: Pull complete
2ab39e99a756: Pull complete
f5dc26e5e1b9: Pull complete
5fcd73766e49: Pull complete
e484236e79c5: Pull complete
91655b2f3252: Pull complete
872af6ae1971: Pull complete
03e4d98756f9: Pull complete
c03f520c9322: Pull complete
e8212007cd85: Pull complete
f3555e597ab1: Pull complete
e92fd14bba9e: Pull complete
5c267b95afa2: Pull complete
b79cf2614cd3: Pull complete
e19ce45db100: Pull complete
279dec3aee98: Pull complete
3bc0af6f8ead: Pull complete
bf22b1bafa35: Pull complete
5fa91ce5a75b: Pull complete
8ad60e5f0ff3: Pull complete
6503ce394424: Pull complete
a2db9d777047: Pull complete
ceae9a1535ad: Pull complete
1803ce8f03ef: Pull complete
838f681ac488: Pull complete
c6a6a1067ea9: Pull complete
4a2c90f7409b: Pull complete
3d96d6142a40: Already exists
83e4dde6b9cf: Already exists
b670fb0c7ecd: Already exists
29460ac93442: Already exists
d2a0ecffe6fa: Already exists
Digest: sha256:ab4a06e6abc130fc4ab4e9aa577dd2be8746d2cfc17a498cf86aed96bd5e45ed
Status: Downloaded newer image for jupyter/systemuser:latest
```

However, I have noticed issues with DNS and Docker Hub, that happen in the middle of downloading. Was this all it reported?
