### ISSUE TITLE
Running Docker daemon on a different machine?

### ISSUE THREAD

**Issue by jhale** [jupyter/dockerspawner#45]
I am using the SystemSpawner. It correctly launches a Docker daemon on a different machine. But then it tries to contact that machine on 127.0.0.1:32842 which obviously is not correct as it is a different machine!

Any hints on how to give it the correct IP?

**Comment by jhamrick** [comment]
The way the SwarmSpawner addresses this is by starting the container, and then setting the IP address after the fact:

https://github.com/compmodels/jupyterhub/blob/master/swarmspawner.py#L60

I think if you know the IP address ahead of time then you should be able to set the `DockerSpawner.container_ip` config option in your `jupyterhub_config.py`:

https://github.com/jupyter/dockerspawner/blob/master/dockerspawner/dockerspawner.py#L63

**Comment by jerrylam** [comment]
@jhamrick How can the swarmspawner launch jupyter docker containers on mesos? I'm thinking of building mesosspawner. Just want to know if you have an idea you mind to share?

**Comment by jhamrick** [comment]
@jerrylam I haven't used Mesos before, so I'm afraid I can't offer any insight on that.

**Comment by rgbkrk** [comment]
@parente has some Mesos background I hear, might be good to collaborate with him and other folks at IBM

**Comment by jtyberg** [comment]
We've run Docker containers on Mesos using their [Docker Containerizer](http://mesos.apache.org/documentation/latest/docker-containerizer/).  We actually use the [Marathon](https://mesosphere.github.io/marathon/docs/native-docker.html) framework on top of Mesos, so we launch the container as a Marathon application using the Marathon REST API.  In the end, we just send a JSON blob describing how to run the container.

Here's a sample of running a single Kafka broker:

```
cat << EOF > /tmp/kafka.json
{
    "id": "kafka",
    "cmd": "KAFKA_ADVERTISED_PORT=${PORT} KAFKA_PORT=${PORT} KAFKA_ADVERTISED_HOST_NAME=`hostname` /start.sh",
    "container": {
        "type": "DOCKER",
        "docker": {
            "image": "ches/kafka",
            "network": "HOST"
        },
        "volumes": [
            {
                "containerPath": "/data",
                "hostPath": "/var/kafka/data",
                "mode": "RW"
            },
            {
                "containerPath": "/logs",
                "hostPath": "/var/kafka/logs",
                "mode": "RO"
            }
        ]
    },
    "ports": [
        0
    ],
    "env": {
        "ZOOKEEPER_IP": "$MASTER_PRIVATE_IP"
    },
    "instances": 1,
    "mem": 256
}
EOF
```

To launch, 

```
curl -X POST -H 'Content-Type: application/json' \
-d @/tmp/kafka.json \
http://$MASTER_PRIVATE_IP:8080/v2/apps
```

**Comment by jlamcanopy** [comment]
@jtyberg That is pretty COOL Thank you for sharing the idea. Do you have a public github repo that has this integration?

**Comment by jtyberg** [comment]
@jlamcanopy My apologies. I should have put some more context around my comment above.  We're using Marathon/Mesos to run Docker containers, but not with jupyter/dockerspawner.   So no, I don't have a repo to point you to.

**Comment by minrk** [comment]
I believe this is fixed by the networks support, where it asks docker for the IP of the container.
