### ISSUE TITLE
Jupyterhub stops all docker containers when it is shutdown

### ISSUE THREAD

**Issue by jlamcanopy** [jupyter/dockerspawner#48]
Hi guys,

I just want to understand if it is required that all docker containers being stopped when jupyterhub is shutdown?

If we only want to stop jupyterhub but let all containers continue to run,, can we reattach jupyterhub to all existing running containers?

Thanks!

**Comment by minrk** [comment]
This is an option. If you specify `c.JupyterHub.cleanup_servers = False` in your config, shutting down the Hub will leave the servers up and reconnect on resume.

**Comment by jlamcanopy** [comment]
@minrk  Perfect! I didn't know we have this config. Thanks for letting me know!
