### ISSUE TITLE
systemuser docker won't build

### ISSUE THREAD

**Issue by richjoyce** [jupyter/dockerspawner#60]
When running `sudo docker build -t jupyter/systemuser systemuser` I run into the following error:
```
Removing intermediate container c469ee26fc12
Step 4 : RUN chmod 755 /usr/local/bin/jupyterhub-singleuser
 ---> Running in 4bb14b3b8391
chmod: changing permissions of ‘/usr/local/bin/jupyterhub-singleuser’: Operation not permitted
The command '/bin/sh -c chmod 755 /usr/local/bin/jupyterhub-singleuser' returned a non-zero code: 1
```

I got around this by putting `USER root` before the `chmod` command in the `Dockerfile` but I don't feel like that is the proper solution...

EDIT: This is on Ubuntu 14.04 with docker 1.9.1, I also tried it with the ubuntu repository version of docker (not sure what version that was) but that failed as well, so I upgraded hoping that was my issue but it wasn't

**Comment by minrk** [comment]
@richjoyce you were on the right track. Should be fixed by #62
