### ISSUE TITLE
Adapt singleuser Docker image to use tini

### ISSUE THREAD

**Issue by rgbkrk** [jupyter/dockerspawner#77]
Wonder if it should just be migrated to be one of the docker-stacks images.

/cc @parente

**Comment by parente** [comment]
https://github.com/jupyter/dockerspawner/blob/master/singleuser/Dockerfile is already `FROM jupyter/scipy-notebook` which is one of the docker-stacks images.

**Comment by rgbkrk** [comment]
D'oh.
